function [Upout]=product_freq_matrices(M,Up,fftsize)
    Upout=[(M(1,1:fftsize).*Up(1,1:fftsize)+M(1,fftsize+1:end).*Up(2,1:fftsize)),...
           (M(1,1:fftsize).*Up(1,fftsize+1:end)+M(1,fftsize+1:end).*Up(2,fftsize+1:end));...
           (M(2,1:fftsize).*Up(1,1:fftsize)+M(2,fftsize+1:end).*Up(2,1:fftsize)),...
           (M(2,1:fftsize).*Up(1,fftsize+1:end)+M(2,fftsize+1:end).*Up(2,fftsize+1:end))];
